### ISSUE TITLE
Game crashing after getting "Invalid OAuth token"

### ISSUE THREAD

**Issue by EnduuS** [mini-bomba/StreamChatMod#1]
Hello! After setting 2FA all previous tokens had been disabled (I guess) and due to that I started getting crashes every single time I tried launching my game.

Log line:
[4:responseBody={"error":"Unauthorized","status":401,"message":"Invalid OAuth token"}]

I wish you a wonderful day and wait patiently for the next version!

**Comment by mini-bomba** [comment]
Please send a crash report so I can correctly fix this issue
