### ISSUE TITLE
[BUG] The colored names are just wrong

### ISSUE THREAD

**Issue by NopoTheGamer** [mini-bomba/StreamChatMod#14]
**Describe the bug**
The colors for the names are just wrong

**Reproduction steps**
1. go to like any twitch chat

**Expected behavior**
The name colors to look like twitch chat

**Environment information**
 - OS: Arch Linux
 - Forge version: 2318
 - Mod version: idk newest 
 - Other installed mods: shouldnt matter right?

note: if you are using additional mods, please make sure this bug can still be replicated without them.
if this bug can only be replicated with additional mods, please use the "Incompatibility report" template instead.

**Additional context**
https://cdn.discordapp.com/attachments/832652653292027904/930265664072081409/unknown.png
https://cdn.discordapp.com/attachments/832652653292027904/930268078309253140/unknown.png
Here i think my name should be aqua

https://cdn.discordapp.com/attachments/832652653292027904/930266383537815582/unknown.png
https://cdn.discordapp.com/attachments/832652653292027904/930266384624123944/unknown.png
Here streamelements should be dark blue, squidy should be red, speedrunner same color as streamelements
https://cdn.discordapp.com/attachments/832652653292027904/930266992039034950/unknown.png
https://cdn.discordapp.com/attachments/832652653292027904/930267016194031676/unknown.png
bird should be light green

**Comment by mini-bomba** [comment]
The colors are never going to be perfect (since we're not on 1.16), but this does seem like they are just not the correct colors. I'm thinking if maybe matching colors using HSV instead of the current RGB would choose better colors.

BTW, here's a markdown tip: Embed images using `![alternative text](image link)`

**Comment by ThatGravyBoat** [comment]
#18 improves this

**Comment by mini-bomba** [comment]
PR #18 has just been merged, which should fix this issue
