### ISSUE TITLE
[BUG] IRC Notices missing

### ISSUE THREAD

**Issue by ThatGravyBoat** [mini-bomba/StreamChatMod#19]
**Describe the bug**
IRC Notices missing for hosting events.

**Reproduction steps**
Host a channel

**Expected behavior**
It should probs say something along the lines of "X Channel is now hosting Y Channel." or "X Channel is no longer hosting a channel."

**Logs & Screenshots**
![image](https://user-images.githubusercontent.com/26934102/148967083-e4306377-d048-4e7b-b184-e9dec7cb05e5.png)

**Environment information**
 - OS: Windows
 - Forge version: 11.15.1.2318
 - Mod version: 1.4.0
 - Other installed mods: None.

**Comment by mini-bomba** [comment]
Just committed a partial rewrite of the NOTICE handler - this message should now only appear for NOTICEs without a message
