### ISSUE TITLE
[BUG] found a bug, plz fix

### ISSUE THREAD

**Issue by aasd24** [mini-bomba/StreamChatMod#2]
**Describe the bug**
you can use the § character to change the formatting of the text in mc twitch chat

**Reproduction steps**
1. type out §<insert formatting characters> and any text after that on twitch's chat

**Expected behavior**
It should normally type out what the viewer said without formatting

**Actual behavior**
It does it with formatting

**Logs & Screenshots**
![image](https://user-images.githubusercontent.com/39914183/122685209-3bd12400-d20a-11eb-9872-3a3e00f82d91.png)
(yes i know 4K ULTRA HD)

**Environment information**
twitch.tv/enduus

**Additional context**
¯\_(ツ)_/¯

**Comment by mini-bomba** [comment]
Commit 7251fe7 fixes this issue:
Formatting codes are now disabled by default, but can be enabled with `/twitch formatting enable`
If enabled, bukkit/spigot/paper-like formatting codes, using `&` instead of `§` are also supported and work.
