### ISSUE TITLE
[BUG] Cannot escape the format character

### ISSUE THREAD

**Issue by mini-bomba** [mini-bomba/StreamChatMod#21]
**Describe the bug**
When chat formatting is enabled, the chat formatting character cannot be escaped by using `&&`

**Reproduction steps**
1. start up the chat
2. enable formatting
3. send a message including an escaped format sequence, such as `&&a`
4. See it not escape the character

**Expected behavior**
`&&a` should be replaced by `&a`

**Actual behavior**
you get `&` and the rest has formatting changed 

**Logs & Screenshots**
If applicable, add logs and/or screenshots to help explain your problem.
![screenshot from minecraft](https://cdn.upload.systems/uploads/lv7y0p6Y.png)
![screenshot from twitch](https://cdn.upload.systems/uploads/rN2rKF6Q.png)

**Environment information**
 - OS: windoz
 - Forge version: idk
 - Mod version: he wont tell me the exact version, but we all know it's *slightly* outdated
 - Other installed mods: a lot
 - got from [EnduuS' stream](https://www.twitch.tv/enduus)

note: if you are using additional mods, please make sure this bug can still be replicated without them.
if this bug can only be replicated with additional mods, please use the "Incompatibility report" template instead.

**Additional context**
found this bug on @EnduuS stream

**Comment by aasd24** [comment]
![image](https://user-images.githubusercontent.com/39914183/151673806-49497340-2928-4857-88e0-52bf93f6b9ee.png)

**Comment by mini-bomba** [comment]
@aasd24 you know, maintainers sometimes also make issues on their own repos to keep track of them when they ~~don't want to~~ can't fix it right away ~~or want another contributor to fix it for them~~

**Comment by m1auch4t** [comment]
> @aasd24 you know, maintainers sometimes also make issues on their own repos to keep track of them when they ~don't want to~ can't fix it right away ~or want another contributor to fix it for them~

When SCM trello

**Comment by aasd24** [comment]
> @aasd24 you know, maintainers sometimes also make issues on their own repos to keep track of them when they ~don't want to~ can't fix it right away ~or want another contributor to fix it for them~

understandable ~~but i just couldn't hold myself~~

**Comment by mini-bomba** [comment]
> When SCM trello

who needs trello, when you have [github projects that integrate with github](https://github.com/mini-bomba/StreamChatMod/projects/1)
