### ISSUE TITLE
[FEATURE] Change cache implementation to Caffeine

### ISSUE THREAD

**Issue by domiehomie** [mini-bomba/StreamChatMod#22]
**Is your feature request related to a problem? Please describe.**
The current cache implementation is basically just a Map and a LinkedList. I feel like a higher performance cache could be beneficial, especially with the larger emote limit we have now. 

**Describe the solution you'd like**
My solution is to use [Caffeine](https://github.com/ben-manes/caffeine), which is a very high performance and easy to use caching library for the caches.

**Comment by mini-bomba** [comment]
Thanks for the suggestion, I'll look into it the next time I decide to work on this project.
