### ISSUE TITLE
[FEATURE] "/twitch stats" command

### ISSUE THREAD

**Issue by EnduuS** [mini-bomba/StreamChatMod#4]
Hello! I just want to suggest an idea related to SCM. The idea is "/twitch stats" command which would show current stats of user's stream. Eventually it could be divided to another subcommands such as "/twitch stats viewers" which would show how many viewers are watching the stream at the moment. Btw. I love eating kebabs and yeah... I know that no one asked B)

**Comment by aasd24** [comment]
Quite a riveting suggestion you have placed here, EnduuS. I'd be keen of increasing the involvement regarding the placed above suggestion towards the creator of the currently talked about Minecraft Modification.

**Comment by mini-bomba** [comment]
I've just committed this in b082a4b.
I added a command: `/twitch streamstats [optional streamer name]` and a shortcut `Show stream statistics`.
They both simply print the stream name, game, viewer count and uptime to the chat.
