### ISSUE TITLE
[FEATURE] Show Badges as their image version instead of words

### ISSUE THREAD

**Issue by NopoTheGamer** [mini-bomba/StreamChatMod#6]
**Is your feature request related to a problem? Please describe.**
The real badges would look cooler 

**Describe the solution you'd like**
I saw there was a method to get the badges of a streamer but I'm too Pepega to add myself
`twitch.getHelix().getChannelChatBadges()`

**Additional context**
[would look smth like this](https://cdn.discordapp.com/attachments/801756364674301953/895067077713494096/unknown.png)

**Comment by mini-bomba** [comment]
Thanks for the idea, the badge icons were already planned, but I'll still add this issue to the project board

**Comment by mini-bomba** [comment]
I've implemented this in commit 8fea193, this should be up in the automatic prereleases soon™
