### ISSUE TITLE
[FEATURE] Add an option that makes emotes work everywhere, not just in twitch output

### ISSUE THREAD

**Issue by domiehomie** [mini-bomba/StreamChatMod#8]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i type a twitch emote in something like the Hypixel guild chat, and its just a slob of text. 

**Describe the solution you'd like**
It would be great if u could make it so you can turn this feature on with a command of some sorts, and maybe even import emotes from a specific streamer? if thats feasible.

**Describe alternatives you've considered**
I have considered looking through the code and making it on my own, but i have no idea what is going on half the time.

**Additional context**
N/A

**Comment by mini-bomba** [comment]
On first thought, this should be possible. I'll see what can be done and will implement this as an opt-in feature

**Comment by mini-bomba** [comment]
I've just implemented this feature in commit [8048971](https://github.com/mini-bomba/StreamChatMod/commit/80489715adfb76f17ec8cf17d38154b271cdd21c).
It should be in the automatic prereleases soon (unless GH Actions fails again)
