### ISSUE TITLE
[BUG] Some messages dont show with badges on

### ISSUE THREAD

**Issue by NopoTheGamer** [mini-bomba/StreamChatMod#9]
**Describe the bug**
Some random peoples messages don't show if you have image badges on

**Reproduction steps**
1. join channel
2. have badges on
3. get people to send messages
4. notice some peoples don't show

**Logs & Screenshots**
[This persons badges worked in my chat](https://cdn.discordapp.com/attachments/832652653292027904/929570750040506368/unknown.png)
[You can see my message sent in throwpo1 but when I posted in my own chat my message didn't show but the bot did](https://cdn.discordapp.com/attachments/832652653292027904/929575675315228733/unknown.png)
[Here you can see everyone with badges don't show](https://cdn.discordapp.com/attachments/702456294874808330/929576073325326367/unknown.png)  [Image 2](https://cdn.discordapp.com/attachments/702456294874808330/929576112743411742/unknown.png)

**Environment information**
 - OS: Windows 11
 - Forge version: 2318
[- Other installed mods:](https://cdn.discordapp.com/attachments/832652653292027904/929577769480904774/unknown.png)
- I tested with just this mod and same thing

note: if you are using additional mods, please make sure this bug can still be replicated without them.
if this bug can only be replicated with additional mods, please use the "Incompatibility report" template instead.

**Additional context**
At first I thought it was just if you had 2 badges but some peoples messages show with 2 badges as well

**Comment by mini-bomba** [comment]
I think those may be the channel badges, which I didn't implement yet... _probably should do that_

**Comment by mini-bomba** [comment]
I've just pushed a [commit](https://github.com/mini-bomba/StreamChatMod/commit/684177654ab0ae9f4d17b6d1d0ce508631d3bd05) which implements channel badges. Can you check if this has fixed the issue?

**Comment by domiehomie** [comment]
> I've just pushed a [commit](https://github.com/mini-bomba/StreamChatMod/commit/684177654ab0ae9f4d17b6d1d0ce508631d3bd05) which implements channel badges. Can you check if this has fixed the issue?

it looks like the GH actions workflow failed uploading it

**Comment by mini-bomba** [comment]
> > I've just pushed a [commit](https://github.com/mini-bomba/StreamChatMod/commit/684177654ab0ae9f4d17b6d1d0ce508631d3bd05) which implements channel badges. Can you check if this has fixed the issue?
> 
> it looks like the GH actions workflow failed uploading it

whoops, that happens _and i have no idea why_
Anyways, I've manually uploaded the file from artifacts to the release

**Comment by NopoTheGamer** [comment]
https://cdn.discordapp.com/attachments/832652653292027904/929737484122873886/unknown.png  https://cdn.discordapp.com/attachments/702456294874808330/929737797441576971/unknown.png Looks like it works

**Comment by mini-bomba** [comment]
Nice then! Closing the issue
